//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/22/24 4:02:21 PM
namespace NAV
{
    
    /// <summary>
    /// There are no comments for NAV in the schema.
    /// </summary>
    public partial class NAV : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new NAV object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NAV(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "NAV", "NAV");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("NAV", global::System.StringComparison.Ordinal))
            {
                return string.Concat("NAV.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Item> Item
        {
            get
            {
                if ((this._Item == null))
                {
                    this._Item = base.CreateQuery<Item>("Item");
                }
                return this._Item;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Item> _Item;
        /// <summary>
        /// There are no comments for PackingHeader in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PackingHeader> PackingHeader
        {
            get
            {
                if ((this._PackingHeader == null))
                {
                    this._PackingHeader = base.CreateQuery<PackingHeader>("PackingHeader");
                }
                return this._PackingHeader;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PackingHeader> _PackingHeader;
        /// <summary>
        /// There are no comments for PackingLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PackingLine> PackingLine
        {
            get
            {
                if ((this._PackingLine == null))
                {
                    this._PackingLine = base.CreateQuery<PackingLine>("PackingLine");
                }
                return this._PackingLine;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PackingLine> _PackingLine;
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Company> Company
        {
            get
            {
                if ((this._Company == null))
                {
                    this._Company = base.CreateQuery<Company>("Company");
                }
                return this._Company;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Company> _Company;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
        /// <summary>
        /// There are no comments for PackingHeader in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPackingHeader(PackingHeader packingHeader)
        {
            base.AddObject("PackingHeader", packingHeader);
        }
        /// <summary>
        /// There are no comments for PackingLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPackingLine(PackingLine packingLine)
        {
            base.AddObject("PackingLine", packingLine);
        }
        /// <summary>
        /// There are no comments for Company in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCompany(Company company)
        {
            base.AddObject("Company", company);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"NAV\" xmlns=\"http://schemas.microsoft.com/ado/2007/05/edm\"><EntityType" +
                " Name=\"Item\"><Key><PropertyRef Name=\"No\" /></Key><Property Name=\"No\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"Item_No_for_Labels\" Type=\"Edm.String\" /><Property Name=\"Qty_per_Carto" +
                "n\" Type=\"Edm.Decimal\" /><Property Name=\"Qty_per_Small_Carton\" Type=\"Edm.Decimal\"" +
                " /><Property Name=\"Last_Date_Modified\" Type=\"Edm.DateTime\" /></EntityType><Entit" +
                "yType Name=\"PackingHeader\"><Key><PropertyRef Name=\"No\" /></Key><Property Name=\"N" +
                "o\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Bill_to_Customer_No\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"Bill_to_Name\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"Bill_to_Name_2\" Type=\"Edm.String\" /><Property Name=\"Ship_to_Code\" Type=\"Edm.S" +
                "tring\" /><Property Name=\"Shipping_Agent_Code\" Type=\"Edm.String\" /><Property Name" +
                "=\"Ship_to_Name\" Type=\"Edm.String\" /><Property Name=\"Ship_to_Name_2\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"Ship_to_Address\" Type=\"Edm.String\" /><Property Name=\"Shi" +
                "p_to_Address_2\" Type=\"Edm.String\" /><Property Name=\"Ship_to_City\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"Ship_to_Contact\" Type=\"Edm.String\" /><Property Name=\"Ship_" +
                "to_Post_Code\" Type=\"Edm.String\" /><Property Name=\"Ship_to_County\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"Ship_to_Country_Code\" Type=\"Edm.String\" /><Property Name=\"" +
                "Ship_to_Phone\" Type=\"Edm.String\" /><Property Name=\"Ship_to_Fax\" Type=\"Edm.String" +
                "\" /><Property Name=\"Total_Cartons\" Type=\"Edm.Int32\" /><Property Name=\"Country_of" +
                "_Origin\" Type=\"Edm.String\" /><Property Name=\"Customer_PO_1\" Type=\"Edm.String\" />" +
                "<Property Name=\"Customer_PO_2\" Type=\"Edm.String\" /><Property Name=\"Customer_PO_3" +
                "\" Type=\"Edm.String\" /><Property Name=\"Customer_PO_4\" Type=\"Edm.String\" /><Proper" +
                "ty Name=\"Customer_PO_5\" Type=\"Edm.String\" /><Property Name=\"Customer_Group_for_R" +
                "ef\" Type=\"Edm.String\" /><Property Name=\"Customer_PO_List\" Type=\"Edm.String\" /><P" +
                "roperty Name=\"Last_Updated_User_ID\" Type=\"Edm.String\" /><Property Name=\"Last_Upd" +
                "ated_Date_Time\" Type=\"Edm.DateTime\" /></EntityType><EntityType Name=\"PackingLine" +
                "\"><Key><PropertyRef Name=\"Document_No\" /><PropertyRef Name=\"Line_No\" /></Key><Pr" +
                "operty Name=\"Document_No\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"L" +
                "ine_No\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Number_of_Cartons\" T" +
                "ype=\"Edm.Int32\" /><Property Name=\"Carton_Shared\" Type=\"Edm.Boolean\" /><Property " +
                "Name=\"Carton_Text\" Type=\"Edm.String\" /><Property Name=\"Item_No\" Type=\"Edm.String" +
                "\" /><Property Name=\"Cross_Reference_No\" Type=\"Edm.String\" /><Property Name=\"Desc" +
                "ription\" Type=\"Edm.String\" /><Property Name=\"Quantity_per_Carton\" Type=\"Edm.Deci" +
                "mal\" /><Property Name=\"Subtotal_Quantity\" Type=\"Edm.Decimal\" /><Property Name=\"C" +
                "ountry_of_Origin\" Type=\"Edm.String\" /><Property Name=\"Qty_to_Ship\" Type=\"Edm.Dec" +
                "imal\" /><Property Name=\"Subtotal_Net_Weight\" Type=\"Edm.Decimal\" /><Property Name" +
                "=\"Subtotal_Gross_Weight\" Type=\"Edm.Decimal\" /><Property Name=\"Group_Quantity\" Ty" +
                "pe=\"Edm.Decimal\" /><Property Name=\"Cross_Reference_Type\" Type=\"Edm.String\" /><Pr" +
                "operty Name=\"Cross_Reference_Type_No\" Type=\"Edm.String\" /><Property Name=\"Source" +
                "_No\" Type=\"Edm.String\" /><Property Name=\"External_Document_No\" Type=\"Edm.String\"" +
                " /></EntityType><EntityType Name=\"Company\"><Key><PropertyRef Name=\"Name\" /></Key" +
                "><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty " +
                "Name=\"Item\" Relationship=\"NAV.Company_Item\" ToRole=\"Item\" FromRole=\"Company\" /><" +
                "NavigationProperty Name=\"PackingHeader\" Relationship=\"NAV.Company_PackingHeader\"" +
                " ToRole=\"PackingHeader\" FromRole=\"Company\" /><NavigationProperty Name=\"PackingLi" +
                "ne\" Relationship=\"NAV.Company_PackingLine\" ToRole=\"PackingLine\" FromRole=\"Compan" +
                "y\" /></EntityType><Association Name=\"Company_Item\"><End Type=\"NAV.Item\" Role=\"It" +
                "em\" Multiplicity=\"*\" /><End Type=\"NAV.Company\" Role=\"Company\" Multiplicity=\"*\" /" +
                "></Association><Association Name=\"Company_PackingHeader\"><End Type=\"NAV.PackingH" +
                "eader\" Role=\"PackingHeader\" Multiplicity=\"*\" /><End Type=\"NAV.Company\" Role=\"Com" +
                "pany\" Multiplicity=\"*\" /></Association><Association Name=\"Company_PackingLine\"><" +
                "End Type=\"NAV.PackingLine\" Role=\"PackingLine\" Multiplicity=\"*\" /><End Type=\"NAV." +
                "Company\" Role=\"Company\" Multiplicity=\"*\" /></Association><EntityContainer Name=\"" +
                "NAV\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Item\" EntityType=\"NAV.It" +
                "em\" /><EntitySet Name=\"PackingHeader\" EntityType=\"NAV.PackingHeader\" /><EntitySe" +
                "t Name=\"PackingLine\" EntityType=\"NAV.PackingLine\" /><EntitySet Name=\"Company\" En" +
                "tityType=\"NAV.Company\" /><AssociationSet Name=\"Company_Item_Item\" Association=\"N" +
                "AV.Company_Item\"><End Role=\"Company\" EntitySet=\"Company\" /><End Role=\"Item\" Enti" +
                "tySet=\"Item\" /></AssociationSet><AssociationSet Name=\"Company_PackingHeader_Pack" +
                "ingHeader\" Association=\"NAV.Company_PackingHeader\"><End Role=\"Company\" EntitySet" +
                "=\"Company\" /><End Role=\"PackingHeader\" EntitySet=\"PackingHeader\" /></Association" +
                "Set><AssociationSet Name=\"Company_PackingLine_PackingLine\" Association=\"NAV.Comp" +
                "any_PackingLine\"><End Role=\"Company\" EntitySet=\"Company\" /><End Role=\"PackingLin" +
                "e\" EntitySet=\"PackingLine\" /></AssociationSet></EntityContainer></Schema></edmx:" +
                "DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for NAV.Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// No
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Item")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("No")]
    public partial class Item : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="no">Initial value of No.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Item CreateItem(string no)
        {
            Item item = new Item();
            item.No = no;
            return item;
        }
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
                this.OnPropertyChanged("No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Item_No_for_Labels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Item_No_for_Labels
        {
            get
            {
                return this._Item_No_for_Labels;
            }
            set
            {
                this.OnItem_No_for_LabelsChanging(value);
                this._Item_No_for_Labels = value;
                this.OnItem_No_for_LabelsChanged();
                this.OnPropertyChanged("Item_No_for_Labels");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Item_No_for_Labels;
        partial void OnItem_No_for_LabelsChanging(string value);
        partial void OnItem_No_for_LabelsChanged();
        /// <summary>
        /// There are no comments for Property Qty_per_Carton in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Qty_per_Carton
        {
            get
            {
                return this._Qty_per_Carton;
            }
            set
            {
                this.OnQty_per_CartonChanging(value);
                this._Qty_per_Carton = value;
                this.OnQty_per_CartonChanged();
                this.OnPropertyChanged("Qty_per_Carton");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Qty_per_Carton;
        partial void OnQty_per_CartonChanging(global::System.Nullable<decimal> value);
        partial void OnQty_per_CartonChanged();
        /// <summary>
        /// There are no comments for Property Qty_per_Small_Carton in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Qty_per_Small_Carton
        {
            get
            {
                return this._Qty_per_Small_Carton;
            }
            set
            {
                this.OnQty_per_Small_CartonChanging(value);
                this._Qty_per_Small_Carton = value;
                this.OnQty_per_Small_CartonChanged();
                this.OnPropertyChanged("Qty_per_Small_Carton");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Qty_per_Small_Carton;
        partial void OnQty_per_Small_CartonChanging(global::System.Nullable<decimal> value);
        partial void OnQty_per_Small_CartonChanged();
        /// <summary>
        /// There are no comments for Property Last_Date_Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Last_Date_Modified
        {
            get
            {
                return this._Last_Date_Modified;
            }
            set
            {
                this.OnLast_Date_ModifiedChanging(value);
                this._Last_Date_Modified = value;
                this.OnLast_Date_ModifiedChanged();
                this.OnPropertyChanged("Last_Date_Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Last_Date_Modified;
        partial void OnLast_Date_ModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLast_Date_ModifiedChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NAV.PackingHeader in the schema.
    /// </summary>
    /// <KeyProperties>
    /// No
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PackingHeader")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("No")]
    public partial class PackingHeader : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PackingHeader object.
        /// </summary>
        /// <param name="no">Initial value of No.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PackingHeader CreatePackingHeader(string no)
        {
            PackingHeader packingHeader = new PackingHeader();
            packingHeader.No = no;
            return packingHeader;
        }
        /// <summary>
        /// There are no comments for Property No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string No
        {
            get
            {
                return this._No;
            }
            set
            {
                this.OnNoChanging(value);
                this._No = value;
                this.OnNoChanged();
                this.OnPropertyChanged("No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _No;
        partial void OnNoChanging(string value);
        partial void OnNoChanged();
        /// <summary>
        /// There are no comments for Property Bill_to_Customer_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bill_to_Customer_No
        {
            get
            {
                return this._Bill_to_Customer_No;
            }
            set
            {
                this.OnBill_to_Customer_NoChanging(value);
                this._Bill_to_Customer_No = value;
                this.OnBill_to_Customer_NoChanged();
                this.OnPropertyChanged("Bill_to_Customer_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bill_to_Customer_No;
        partial void OnBill_to_Customer_NoChanging(string value);
        partial void OnBill_to_Customer_NoChanged();
        /// <summary>
        /// There are no comments for Property Bill_to_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bill_to_Name
        {
            get
            {
                return this._Bill_to_Name;
            }
            set
            {
                this.OnBill_to_NameChanging(value);
                this._Bill_to_Name = value;
                this.OnBill_to_NameChanged();
                this.OnPropertyChanged("Bill_to_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bill_to_Name;
        partial void OnBill_to_NameChanging(string value);
        partial void OnBill_to_NameChanged();
        /// <summary>
        /// There are no comments for Property Bill_to_Name_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bill_to_Name_2
        {
            get
            {
                return this._Bill_to_Name_2;
            }
            set
            {
                this.OnBill_to_Name_2Changing(value);
                this._Bill_to_Name_2 = value;
                this.OnBill_to_Name_2Changed();
                this.OnPropertyChanged("Bill_to_Name_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bill_to_Name_2;
        partial void OnBill_to_Name_2Changing(string value);
        partial void OnBill_to_Name_2Changed();
        /// <summary>
        /// There are no comments for Property Ship_to_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Code
        {
            get
            {
                return this._Ship_to_Code;
            }
            set
            {
                this.OnShip_to_CodeChanging(value);
                this._Ship_to_Code = value;
                this.OnShip_to_CodeChanged();
                this.OnPropertyChanged("Ship_to_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Code;
        partial void OnShip_to_CodeChanging(string value);
        partial void OnShip_to_CodeChanged();
        /// <summary>
        /// There are no comments for Property Shipping_Agent_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Shipping_Agent_Code
        {
            get
            {
                return this._Shipping_Agent_Code;
            }
            set
            {
                this.OnShipping_Agent_CodeChanging(value);
                this._Shipping_Agent_Code = value;
                this.OnShipping_Agent_CodeChanged();
                this.OnPropertyChanged("Shipping_Agent_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Shipping_Agent_Code;
        partial void OnShipping_Agent_CodeChanging(string value);
        partial void OnShipping_Agent_CodeChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Name
        {
            get
            {
                return this._Ship_to_Name;
            }
            set
            {
                this.OnShip_to_NameChanging(value);
                this._Ship_to_Name = value;
                this.OnShip_to_NameChanged();
                this.OnPropertyChanged("Ship_to_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Name;
        partial void OnShip_to_NameChanging(string value);
        partial void OnShip_to_NameChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Name_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Name_2
        {
            get
            {
                return this._Ship_to_Name_2;
            }
            set
            {
                this.OnShip_to_Name_2Changing(value);
                this._Ship_to_Name_2 = value;
                this.OnShip_to_Name_2Changed();
                this.OnPropertyChanged("Ship_to_Name_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Name_2;
        partial void OnShip_to_Name_2Changing(string value);
        partial void OnShip_to_Name_2Changed();
        /// <summary>
        /// There are no comments for Property Ship_to_Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Address
        {
            get
            {
                return this._Ship_to_Address;
            }
            set
            {
                this.OnShip_to_AddressChanging(value);
                this._Ship_to_Address = value;
                this.OnShip_to_AddressChanged();
                this.OnPropertyChanged("Ship_to_Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Address;
        partial void OnShip_to_AddressChanging(string value);
        partial void OnShip_to_AddressChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Address_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Address_2
        {
            get
            {
                return this._Ship_to_Address_2;
            }
            set
            {
                this.OnShip_to_Address_2Changing(value);
                this._Ship_to_Address_2 = value;
                this.OnShip_to_Address_2Changed();
                this.OnPropertyChanged("Ship_to_Address_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Address_2;
        partial void OnShip_to_Address_2Changing(string value);
        partial void OnShip_to_Address_2Changed();
        /// <summary>
        /// There are no comments for Property Ship_to_City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_City
        {
            get
            {
                return this._Ship_to_City;
            }
            set
            {
                this.OnShip_to_CityChanging(value);
                this._Ship_to_City = value;
                this.OnShip_to_CityChanged();
                this.OnPropertyChanged("Ship_to_City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_City;
        partial void OnShip_to_CityChanging(string value);
        partial void OnShip_to_CityChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Contact
        {
            get
            {
                return this._Ship_to_Contact;
            }
            set
            {
                this.OnShip_to_ContactChanging(value);
                this._Ship_to_Contact = value;
                this.OnShip_to_ContactChanged();
                this.OnPropertyChanged("Ship_to_Contact");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Contact;
        partial void OnShip_to_ContactChanging(string value);
        partial void OnShip_to_ContactChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Post_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Post_Code
        {
            get
            {
                return this._Ship_to_Post_Code;
            }
            set
            {
                this.OnShip_to_Post_CodeChanging(value);
                this._Ship_to_Post_Code = value;
                this.OnShip_to_Post_CodeChanged();
                this.OnPropertyChanged("Ship_to_Post_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Post_Code;
        partial void OnShip_to_Post_CodeChanging(string value);
        partial void OnShip_to_Post_CodeChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_County in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_County
        {
            get
            {
                return this._Ship_to_County;
            }
            set
            {
                this.OnShip_to_CountyChanging(value);
                this._Ship_to_County = value;
                this.OnShip_to_CountyChanged();
                this.OnPropertyChanged("Ship_to_County");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_County;
        partial void OnShip_to_CountyChanging(string value);
        partial void OnShip_to_CountyChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Country_Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Country_Code
        {
            get
            {
                return this._Ship_to_Country_Code;
            }
            set
            {
                this.OnShip_to_Country_CodeChanging(value);
                this._Ship_to_Country_Code = value;
                this.OnShip_to_Country_CodeChanged();
                this.OnPropertyChanged("Ship_to_Country_Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Country_Code;
        partial void OnShip_to_Country_CodeChanging(string value);
        partial void OnShip_to_Country_CodeChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Phone
        {
            get
            {
                return this._Ship_to_Phone;
            }
            set
            {
                this.OnShip_to_PhoneChanging(value);
                this._Ship_to_Phone = value;
                this.OnShip_to_PhoneChanged();
                this.OnPropertyChanged("Ship_to_Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Phone;
        partial void OnShip_to_PhoneChanging(string value);
        partial void OnShip_to_PhoneChanged();
        /// <summary>
        /// There are no comments for Property Ship_to_Fax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ship_to_Fax
        {
            get
            {
                return this._Ship_to_Fax;
            }
            set
            {
                this.OnShip_to_FaxChanging(value);
                this._Ship_to_Fax = value;
                this.OnShip_to_FaxChanged();
                this.OnPropertyChanged("Ship_to_Fax");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ship_to_Fax;
        partial void OnShip_to_FaxChanging(string value);
        partial void OnShip_to_FaxChanged();
        /// <summary>
        /// There are no comments for Property Total_Cartons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Total_Cartons
        {
            get
            {
                return this._Total_Cartons;
            }
            set
            {
                this.OnTotal_CartonsChanging(value);
                this._Total_Cartons = value;
                this.OnTotal_CartonsChanged();
                this.OnPropertyChanged("Total_Cartons");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Total_Cartons;
        partial void OnTotal_CartonsChanging(global::System.Nullable<int> value);
        partial void OnTotal_CartonsChanged();
        /// <summary>
        /// There are no comments for Property Country_of_Origin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_of_Origin
        {
            get
            {
                return this._Country_of_Origin;
            }
            set
            {
                this.OnCountry_of_OriginChanging(value);
                this._Country_of_Origin = value;
                this.OnCountry_of_OriginChanged();
                this.OnPropertyChanged("Country_of_Origin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_of_Origin;
        partial void OnCountry_of_OriginChanging(string value);
        partial void OnCountry_of_OriginChanged();
        /// <summary>
        /// There are no comments for Property Customer_PO_1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_1
        {
            get
            {
                return this._Customer_PO_1;
            }
            set
            {
                this.OnCustomer_PO_1Changing(value);
                this._Customer_PO_1 = value;
                this.OnCustomer_PO_1Changed();
                this.OnPropertyChanged("Customer_PO_1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_1;
        partial void OnCustomer_PO_1Changing(string value);
        partial void OnCustomer_PO_1Changed();
        /// <summary>
        /// There are no comments for Property Customer_PO_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_2
        {
            get
            {
                return this._Customer_PO_2;
            }
            set
            {
                this.OnCustomer_PO_2Changing(value);
                this._Customer_PO_2 = value;
                this.OnCustomer_PO_2Changed();
                this.OnPropertyChanged("Customer_PO_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_2;
        partial void OnCustomer_PO_2Changing(string value);
        partial void OnCustomer_PO_2Changed();
        /// <summary>
        /// There are no comments for Property Customer_PO_3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_3
        {
            get
            {
                return this._Customer_PO_3;
            }
            set
            {
                this.OnCustomer_PO_3Changing(value);
                this._Customer_PO_3 = value;
                this.OnCustomer_PO_3Changed();
                this.OnPropertyChanged("Customer_PO_3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_3;
        partial void OnCustomer_PO_3Changing(string value);
        partial void OnCustomer_PO_3Changed();
        /// <summary>
        /// There are no comments for Property Customer_PO_4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_4
        {
            get
            {
                return this._Customer_PO_4;
            }
            set
            {
                this.OnCustomer_PO_4Changing(value);
                this._Customer_PO_4 = value;
                this.OnCustomer_PO_4Changed();
                this.OnPropertyChanged("Customer_PO_4");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_4;
        partial void OnCustomer_PO_4Changing(string value);
        partial void OnCustomer_PO_4Changed();
        /// <summary>
        /// There are no comments for Property Customer_PO_5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_5
        {
            get
            {
                return this._Customer_PO_5;
            }
            set
            {
                this.OnCustomer_PO_5Changing(value);
                this._Customer_PO_5 = value;
                this.OnCustomer_PO_5Changed();
                this.OnPropertyChanged("Customer_PO_5");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_5;
        partial void OnCustomer_PO_5Changing(string value);
        partial void OnCustomer_PO_5Changed();
        /// <summary>
        /// There are no comments for Property Customer_Group_for_Ref in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_Group_for_Ref
        {
            get
            {
                return this._Customer_Group_for_Ref;
            }
            set
            {
                this.OnCustomer_Group_for_RefChanging(value);
                this._Customer_Group_for_Ref = value;
                this.OnCustomer_Group_for_RefChanged();
                this.OnPropertyChanged("Customer_Group_for_Ref");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_Group_for_Ref;
        partial void OnCustomer_Group_for_RefChanging(string value);
        partial void OnCustomer_Group_for_RefChanged();
        /// <summary>
        /// There are no comments for Property Customer_PO_List in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Customer_PO_List
        {
            get
            {
                return this._Customer_PO_List;
            }
            set
            {
                this.OnCustomer_PO_ListChanging(value);
                this._Customer_PO_List = value;
                this.OnCustomer_PO_ListChanged();
                this.OnPropertyChanged("Customer_PO_List");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Customer_PO_List;
        partial void OnCustomer_PO_ListChanging(string value);
        partial void OnCustomer_PO_ListChanged();
        /// <summary>
        /// There are no comments for Property Last_Updated_User_ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Last_Updated_User_ID
        {
            get
            {
                return this._Last_Updated_User_ID;
            }
            set
            {
                this.OnLast_Updated_User_IDChanging(value);
                this._Last_Updated_User_ID = value;
                this.OnLast_Updated_User_IDChanged();
                this.OnPropertyChanged("Last_Updated_User_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Last_Updated_User_ID;
        partial void OnLast_Updated_User_IDChanging(string value);
        partial void OnLast_Updated_User_IDChanged();
        /// <summary>
        /// There are no comments for Property Last_Updated_Date_Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Last_Updated_Date_Time
        {
            get
            {
                return this._Last_Updated_Date_Time;
            }
            set
            {
                this.OnLast_Updated_Date_TimeChanging(value);
                this._Last_Updated_Date_Time = value;
                this.OnLast_Updated_Date_TimeChanged();
                this.OnPropertyChanged("Last_Updated_Date_Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Last_Updated_Date_Time;
        partial void OnLast_Updated_Date_TimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLast_Updated_Date_TimeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NAV.PackingLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Document_No
    /// Line_No
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PackingLine")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Document_No", "Line_No")]
    public partial class PackingLine : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PackingLine object.
        /// </summary>
        /// <param name="document_No">Initial value of Document_No.</param>
        /// <param name="line_No">Initial value of Line_No.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PackingLine CreatePackingLine(string document_No, int line_No)
        {
            PackingLine packingLine = new PackingLine();
            packingLine.Document_No = document_No;
            packingLine.Line_No = line_No;
            return packingLine;
        }
        /// <summary>
        /// There are no comments for Property Document_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Document_No
        {
            get
            {
                return this._Document_No;
            }
            set
            {
                this.OnDocument_NoChanging(value);
                this._Document_No = value;
                this.OnDocument_NoChanged();
                this.OnPropertyChanged("Document_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Document_No;
        partial void OnDocument_NoChanging(string value);
        partial void OnDocument_NoChanged();
        /// <summary>
        /// There are no comments for Property Line_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Line_No
        {
            get
            {
                return this._Line_No;
            }
            set
            {
                this.OnLine_NoChanging(value);
                this._Line_No = value;
                this.OnLine_NoChanged();
                this.OnPropertyChanged("Line_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Line_No;
        partial void OnLine_NoChanging(int value);
        partial void OnLine_NoChanged();
        /// <summary>
        /// There are no comments for Property Number_of_Cartons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Number_of_Cartons
        {
            get
            {
                return this._Number_of_Cartons;
            }
            set
            {
                this.OnNumber_of_CartonsChanging(value);
                this._Number_of_Cartons = value;
                this.OnNumber_of_CartonsChanged();
                this.OnPropertyChanged("Number_of_Cartons");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Number_of_Cartons;
        partial void OnNumber_of_CartonsChanging(global::System.Nullable<int> value);
        partial void OnNumber_of_CartonsChanged();
        /// <summary>
        /// There are no comments for Property Carton_Shared in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Carton_Shared
        {
            get
            {
                return this._Carton_Shared;
            }
            set
            {
                this.OnCarton_SharedChanging(value);
                this._Carton_Shared = value;
                this.OnCarton_SharedChanged();
                this.OnPropertyChanged("Carton_Shared");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Carton_Shared;
        partial void OnCarton_SharedChanging(global::System.Nullable<bool> value);
        partial void OnCarton_SharedChanged();
        /// <summary>
        /// There are no comments for Property Carton_Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Carton_Text
        {
            get
            {
                return this._Carton_Text;
            }
            set
            {
                this.OnCarton_TextChanging(value);
                this._Carton_Text = value;
                this.OnCarton_TextChanged();
                this.OnPropertyChanged("Carton_Text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Carton_Text;
        partial void OnCarton_TextChanging(string value);
        partial void OnCarton_TextChanged();
        /// <summary>
        /// There are no comments for Property Item_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Item_No
        {
            get
            {
                return this._Item_No;
            }
            set
            {
                this.OnItem_NoChanging(value);
                this._Item_No = value;
                this.OnItem_NoChanged();
                this.OnPropertyChanged("Item_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Item_No;
        partial void OnItem_NoChanging(string value);
        partial void OnItem_NoChanged();
        /// <summary>
        /// There are no comments for Property Cross_Reference_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Cross_Reference_No
        {
            get
            {
                return this._Cross_Reference_No;
            }
            set
            {
                this.OnCross_Reference_NoChanging(value);
                this._Cross_Reference_No = value;
                this.OnCross_Reference_NoChanged();
                this.OnPropertyChanged("Cross_Reference_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Cross_Reference_No;
        partial void OnCross_Reference_NoChanging(string value);
        partial void OnCross_Reference_NoChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Quantity_per_Carton in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Quantity_per_Carton
        {
            get
            {
                return this._Quantity_per_Carton;
            }
            set
            {
                this.OnQuantity_per_CartonChanging(value);
                this._Quantity_per_Carton = value;
                this.OnQuantity_per_CartonChanged();
                this.OnPropertyChanged("Quantity_per_Carton");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Quantity_per_Carton;
        partial void OnQuantity_per_CartonChanging(global::System.Nullable<decimal> value);
        partial void OnQuantity_per_CartonChanged();
        /// <summary>
        /// There are no comments for Property Subtotal_Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Subtotal_Quantity
        {
            get
            {
                return this._Subtotal_Quantity;
            }
            set
            {
                this.OnSubtotal_QuantityChanging(value);
                this._Subtotal_Quantity = value;
                this.OnSubtotal_QuantityChanged();
                this.OnPropertyChanged("Subtotal_Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Subtotal_Quantity;
        partial void OnSubtotal_QuantityChanging(global::System.Nullable<decimal> value);
        partial void OnSubtotal_QuantityChanged();
        /// <summary>
        /// There are no comments for Property Country_of_Origin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_of_Origin
        {
            get
            {
                return this._Country_of_Origin;
            }
            set
            {
                this.OnCountry_of_OriginChanging(value);
                this._Country_of_Origin = value;
                this.OnCountry_of_OriginChanged();
                this.OnPropertyChanged("Country_of_Origin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_of_Origin;
        partial void OnCountry_of_OriginChanging(string value);
        partial void OnCountry_of_OriginChanged();
        /// <summary>
        /// There are no comments for Property Qty_to_Ship in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Qty_to_Ship
        {
            get
            {
                return this._Qty_to_Ship;
            }
            set
            {
                this.OnQty_to_ShipChanging(value);
                this._Qty_to_Ship = value;
                this.OnQty_to_ShipChanged();
                this.OnPropertyChanged("Qty_to_Ship");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Qty_to_Ship;
        partial void OnQty_to_ShipChanging(global::System.Nullable<decimal> value);
        partial void OnQty_to_ShipChanged();
        /// <summary>
        /// There are no comments for Property Subtotal_Net_Weight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Subtotal_Net_Weight
        {
            get
            {
                return this._Subtotal_Net_Weight;
            }
            set
            {
                this.OnSubtotal_Net_WeightChanging(value);
                this._Subtotal_Net_Weight = value;
                this.OnSubtotal_Net_WeightChanged();
                this.OnPropertyChanged("Subtotal_Net_Weight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Subtotal_Net_Weight;
        partial void OnSubtotal_Net_WeightChanging(global::System.Nullable<decimal> value);
        partial void OnSubtotal_Net_WeightChanged();
        /// <summary>
        /// There are no comments for Property Subtotal_Gross_Weight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Subtotal_Gross_Weight
        {
            get
            {
                return this._Subtotal_Gross_Weight;
            }
            set
            {
                this.OnSubtotal_Gross_WeightChanging(value);
                this._Subtotal_Gross_Weight = value;
                this.OnSubtotal_Gross_WeightChanged();
                this.OnPropertyChanged("Subtotal_Gross_Weight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Subtotal_Gross_Weight;
        partial void OnSubtotal_Gross_WeightChanging(global::System.Nullable<decimal> value);
        partial void OnSubtotal_Gross_WeightChanged();
        /// <summary>
        /// There are no comments for Property Group_Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Group_Quantity
        {
            get
            {
                return this._Group_Quantity;
            }
            set
            {
                this.OnGroup_QuantityChanging(value);
                this._Group_Quantity = value;
                this.OnGroup_QuantityChanged();
                this.OnPropertyChanged("Group_Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Group_Quantity;
        partial void OnGroup_QuantityChanging(global::System.Nullable<decimal> value);
        partial void OnGroup_QuantityChanged();
        /// <summary>
        /// There are no comments for Property Cross_Reference_Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Cross_Reference_Type
        {
            get
            {
                return this._Cross_Reference_Type;
            }
            set
            {
                this.OnCross_Reference_TypeChanging(value);
                this._Cross_Reference_Type = value;
                this.OnCross_Reference_TypeChanged();
                this.OnPropertyChanged("Cross_Reference_Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Cross_Reference_Type;
        partial void OnCross_Reference_TypeChanging(string value);
        partial void OnCross_Reference_TypeChanged();
        /// <summary>
        /// There are no comments for Property Cross_Reference_Type_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Cross_Reference_Type_No
        {
            get
            {
                return this._Cross_Reference_Type_No;
            }
            set
            {
                this.OnCross_Reference_Type_NoChanging(value);
                this._Cross_Reference_Type_No = value;
                this.OnCross_Reference_Type_NoChanged();
                this.OnPropertyChanged("Cross_Reference_Type_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Cross_Reference_Type_No;
        partial void OnCross_Reference_Type_NoChanging(string value);
        partial void OnCross_Reference_Type_NoChanged();
        /// <summary>
        /// There are no comments for Property Source_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Source_No
        {
            get
            {
                return this._Source_No;
            }
            set
            {
                this.OnSource_NoChanging(value);
                this._Source_No = value;
                this.OnSource_NoChanged();
                this.OnPropertyChanged("Source_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Source_No;
        partial void OnSource_NoChanging(string value);
        partial void OnSource_NoChanged();
        /// <summary>
        /// There are no comments for Property External_Document_No in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string External_Document_No
        {
            get
            {
                return this._External_Document_No;
            }
            set
            {
                this.OnExternal_Document_NoChanging(value);
                this._External_Document_No = value;
                this.OnExternal_Document_NoChanged();
                this.OnPropertyChanged("External_Document_No");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _External_Document_No;
        partial void OnExternal_Document_NoChanging(string value);
        partial void OnExternal_Document_NoChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for NAV.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Company")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class Company : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(string name)
        {
            Company company = new Company();
            company.Name = name;
            return company;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Item> Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this._Item = value;
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Item> _Item = new global::System.Data.Services.Client.DataServiceCollection<Item>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for PackingHeader in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PackingHeader> PackingHeader
        {
            get
            {
                return this._PackingHeader;
            }
            set
            {
                this._PackingHeader = value;
                this.OnPropertyChanged("PackingHeader");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PackingHeader> _PackingHeader = new global::System.Data.Services.Client.DataServiceCollection<PackingHeader>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for PackingLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PackingLine> PackingLine
        {
            get
            {
                return this._PackingLine;
            }
            set
            {
                this._PackingLine = value;
                this.OnPropertyChanged("PackingLine");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PackingLine> _PackingLine = new global::System.Data.Services.Client.DataServiceCollection<PackingLine>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
