'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 11/06/23 2:45:36 PM
Namespace NAV
    '''<summary>
    '''There are no comments for NAV in the schema.
    '''</summary>
    Partial Public Class NAV
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new NAV object.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot, Global.System.Data.Services.Common.DataServiceProtocolVersion.V3)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
            Me.Format.LoadServiceModel = AddressOf GeneratedEdmModel.GetInstance
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(NAV).Namespace.Remove(GetType(NAV).Namespace.LastIndexOf("NAV"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            Dim resolvedType As Global.System.Type = Me.DefaultResolveType(typeName, "NAV", String.Concat(ROOTNAMESPACE, "NAV"))
            If (Not (resolvedType) Is Nothing) Then
                Return resolvedType
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "NAV"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("NAV.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Item in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Item() As Global.System.Data.Services.Client.DataServiceQuery(Of Item)
            Get
                If (Me._Item Is Nothing) Then
                    Me._Item = MyBase.CreateQuery(Of Item)("Item")
                End If
                Return Me._Item
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Item As Global.System.Data.Services.Client.DataServiceQuery(Of Item)
        '''<summary>
        '''There are no comments for Company in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Company() As Global.System.Data.Services.Client.DataServiceQuery(Of Company)
            Get
                If (Me._Company Is Nothing) Then
                    Me._Company = MyBase.CreateQuery(Of Company)("Company")
                End If
                Return Me._Company
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Company As Global.System.Data.Services.Client.DataServiceQuery(Of Company)
        '''<summary>
        '''There are no comments for Item in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToItem(ByVal item As Item)
            MyBase.AddObject("Item", item)
        End Sub
        '''<summary>
        '''There are no comments for Company in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToCompany(ByVal company As Company)
            MyBase.AddObject("Company", company)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private MustInherit Class GeneratedEdmModel
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared ParsedModel As Global.Microsoft.Data.Edm.IEdmModel = LoadModelFromString
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Const ModelPart0 As String = "<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edm"& _ 
                "x""><edmx:DataServices m:DataServiceVersion=""1.0"" m:MaxDataServiceVersion=""3.0"" x"& _ 
                "mlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema "& _ 
                "Namespace=""NAV"" xmlns=""http://schemas.microsoft.com/ado/2007/05/edm""><EntityType"& _ 
                " Name=""Item""><Key><PropertyRef Name=""No"" /></Key><Property Name=""No"" Type=""Edm.S"& _ 
                "tring"" Nullable=""false"" /><Property Name=""Item_No_for_Labels"" Type=""Edm.String"" "& _ 
                "/><Property Name=""Qty_per_Carton"" Type=""Edm.Decimal"" /><Property Name=""Qty_per_S"& _ 
                "mall_Carton"" Type=""Edm.Decimal"" /><Property Name=""Last_Date_Modified"" Type=""Edm."& _ 
                "DateTime"" /></EntityType><EntityType Name=""Company""><Key><PropertyRef Name=""Name"& _ 
                """ /></Key><Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" /><Navigation"& _ 
                "Property Name=""Item"" Relationship=""NAV.Company_Item"" ToRole=""Item"" FromRole=""Com"& _ 
                "pany"" /></EntityType><Association Name=""Company_Item""><End Type=""NAV.Item"" Role="& _ 
                """Item"" Multiplicity=""*"" /><End Type=""NAV.Company"" Role=""Company"" Multiplicity=""*"& _ 
                """ /></Association><EntityContainer Name=""NAV"" m:IsDefaultEntityContainer=""true"">"& _ 
                "<EntitySet Name=""Item"" EntityType=""NAV.Item"" /><EntitySet Name=""Company"" EntityT"& _ 
                "ype=""NAV.Company"" /><AssociationSet Name=""Company_Item_Item"" Association=""NAV.Co"& _ 
                "mpany_Item""><End Role=""Company"" EntitySet=""Company"" /><End Role=""Item"" EntitySet"& _ 
                "=""Item"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx"& _ 
                ":Edmx>"
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function GetConcatenatedEdmxString() As String
                Return String.Concat(ModelPart0)
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Public Shared Function GetInstance() As Global.Microsoft.Data.Edm.IEdmModel
                Return ParsedModel
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function LoadModelFromString() As Global.Microsoft.Data.Edm.IEdmModel
                Dim edmxToParse As String = GetConcatenatedEdmxString
                Dim reader As Global.System.Xml.XmlReader = CreateXmlReader(edmxToParse)
                Try 
                    Return Global.Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader)
                Finally
                    CType(reader,Global.System.IDisposable).Dispose
                End Try
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function CreateXmlReader(ByVal edmxToParse As String) As Global.System.Xml.XmlReader
                Return Global.System.Xml.XmlReader.Create(New Global.System.IO.StringReader(edmxToParse))
            End Function
        End Class
    End Class
    '''<summary>
    '''There are no comments for NAV.Item in the schema.
    '''</summary>
    '''<KeyProperties>
    '''No
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Item"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("No")>  _
    Partial Public Class Item
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Item object.
        '''</summary>
        '''<param name="no">Initial value of No.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateItem(ByVal no As String) As Item
            Dim item As Item = New Item()
            item.No = no
            Return item
        End Function
        '''<summary>
        '''There are no comments for Property No in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property No() As String
            Get
                Return Me._No
            End Get
            Set
                Me.OnNoChanging(value)
                Me._No = value
                Me.OnNoChanged
                Me.OnPropertyChanged("No")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _No As String
        Partial Private Sub OnNoChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNoChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Item_No_for_Labels in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Item_No_for_Labels() As String
            Get
                Return Me._Item_No_for_Labels
            End Get
            Set
                Me.OnItem_No_for_LabelsChanging(value)
                Me._Item_No_for_Labels = value
                Me.OnItem_No_for_LabelsChanged
                Me.OnPropertyChanged("Item_No_for_Labels")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Item_No_for_Labels As String
        Partial Private Sub OnItem_No_for_LabelsChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnItem_No_for_LabelsChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Qty_per_Carton in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Qty_per_Carton() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._Qty_per_Carton
            End Get
            Set
                Me.OnQty_per_CartonChanging(value)
                Me._Qty_per_Carton = value
                Me.OnQty_per_CartonChanged
                Me.OnPropertyChanged("Qty_per_Carton")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Qty_per_Carton As Global.System.Nullable(Of Decimal)
        Partial Private Sub OnQty_per_CartonChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        Partial Private Sub OnQty_per_CartonChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Qty_per_Small_Carton in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Qty_per_Small_Carton() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._Qty_per_Small_Carton
            End Get
            Set
                Me.OnQty_per_Small_CartonChanging(value)
                Me._Qty_per_Small_Carton = value
                Me.OnQty_per_Small_CartonChanged
                Me.OnPropertyChanged("Qty_per_Small_Carton")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Qty_per_Small_Carton As Global.System.Nullable(Of Decimal)
        Partial Private Sub OnQty_per_Small_CartonChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        Partial Private Sub OnQty_per_Small_CartonChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Last_Date_Modified in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Last_Date_Modified() As Global.System.Nullable(Of Date)
            Get
                Return Me._Last_Date_Modified
            End Get
            Set
                Me.OnLast_Date_ModifiedChanging(value)
                Me._Last_Date_Modified = value
                Me.OnLast_Date_ModifiedChanged
                Me.OnPropertyChanged("Last_Date_Modified")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Last_Date_Modified As Global.System.Nullable(Of Date)
        Partial Private Sub OnLast_Date_ModifiedChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnLast_Date_ModifiedChanged()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NAV.Company in the schema.
    '''</summary>
    '''<KeyProperties>
    '''Name
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Company"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Name")>  _
    Partial Public Class Company
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Company object.
        '''</summary>
        '''<param name="name">Initial value of Name.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateCompany(ByVal name As String) As Company
            Dim company As Company = New Company()
            company.Name = name
            Return company
        End Function
        '''<summary>
        '''There are no comments for Property Name in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Name() As String
            Get
                Return Me._Name
            End Get
            Set
                Me.OnNameChanging(value)
                Me._Name = value
                Me.OnNameChanged
                Me.OnPropertyChanged("Name")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Name As String
        Partial Private Sub OnNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Item in the schema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Item() As Global.System.Data.Services.Client.DataServiceCollection(Of Item)
            Get
                Return Me._Item
            End Get
            Set
                Me._Item = value
                Me.OnPropertyChanged("Item")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Item As Global.System.Data.Services.Client.DataServiceCollection(Of Item) = New Global.System.Data.Services.Client.DataServiceCollection(Of Item)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
